name: movies_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_rating_bar: ^4.0.1
  get_it: ^8.2.0
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.0.12

  readmore: ^3.0.0
  shimmer: ^3.0.0
  stream_transform: ^2.1.0
  url_launcher: ^6.1.8

dev_dependencies:

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/unnamed.png
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/unnamed.png"
  remove_alpha_ios: true
